export const AppStrings = {
  welcome_to_bikeLink: 'Welcome to BikeLink',
  turn_lights_that_turn_heads: 'Turn lights that turn heads.',
  sign_in: 'Sign In',
  email_address: 'Email',
  enter_email_address: 'Enter Email Address',
  password: 'Password',
  enter_password: 'Enter Password',
  go_back: 'Go Back',
  forgot_your_password: 'Forgot your password?',
  reset_it_here: 'Reset it here',
  reset_pasword: 'Reset Pasword',
  send_reset_link: 'Send Reset Link',
  confirm_password: 'Confirm Password',
  please_enter_the_email_address: 'Please enter the email address.',
  please_enter_valid_email_address: "Please enter a valid email address.",
  please_enter_the_password: 'Please enter the password.',
  the_password_must_be_at_least: 'The password must be at least 8 characters with at least one letter, number and special character.',
  please_enter_the_cpassword: 'Please enter the confirm password.',
  the_entered_passwords_do_not_match: 'The entered passwords do not match.',
  please_enter_the_email_and_password: 'Please enter the email and password.',

  patent_pending: 'Patent Pending',
  welcome_lets_get_started: "Welcome, Let’s get\nstarted!",
  create_an_account: 'Create an Account',
  full_name: 'Full Name',
  company_name: 'Company Name',
  create_account: 'Create Account',
  contact_number: 'Contact Number',
  enter_full_name: 'Enter Full Name',
  enter_company_name: 'Enter Company Name',
  enter_contact_number: 'Enter Contact Number',
  enter_confirm_password: 'Enter Confirm Password',
  please_enter_the_full_name: "Please enter the full name.",
  please_enter_the_company_name: 'Please enter the company name.',
  please_enter_the_contact_number: 'Please enter the contact number.',
  please_enter_least_of_ten_number: 'Please enter least of 10 number.',
  enter_your_email_address_to_receive_a_reset_link: 'Enter your email\naddress to receive a\nreset link',
  forgot_password:'Forgot Password',
  terms_of_service:'Terms of Service',
  privacy_policy: 'Privacy Policy',
  the_email_field_is_required: 'The “Email” field is required.',
  the_full_name_field_is_required: "The “Full Name” field is required.",
  the_company_name_field_is_required: 'The “Company Name” field is required.',
  the_license_number_field_is_required: 'The “License Number” field is required.',
  the_contact_number_field_is_required: 'The “Contact Number” field is required.',
  the_password_field_is_required: "The “Password” field is required.",
  the_confirm_password_field_is_required: 'The “Confirm Password” field is required.',
  password_must_contain_at: 'Password must contain at least 8 characters, one number, one uppercase letter and one special character.',
  enter_ten_digits: 'Enter 10 digits.',
  you_need_to_agree_to_our_Terms_of_Service_and_Privacy_Policy_to_create_an_account: 'You need to agree to our Terms of Service and Privacy Policy to create an account.',
  license_number: 'License Number',
  enter_license_number: 'Enter License Number',
}
