export const AppStrings = {
  welcome_to_bikeLink: 'Welcome to BikeLink',
  turn_lights_that_turn_heads: 'Turn lights that turn heads.',
  sign_in: 'Sign In',
  email_address: 'Email',
  enter_email_address: 'Enter Email Address',
  password: 'Password',
  enter_password: 'Enter Password',
  go_back: 'Go Back',
  forgot_your_password: 'Forgot your password?',
  reset_it_here: 'Reset it here',
  reset_pasword: 'Reset Pasword',
  send_reset_link: 'Send Reset Link',
  confirm_password: 'Confirm Password',
  please_enter_the_email_address: 'Please enter the email address.',
  please_enter_valid_email_address: "The entered email is incorrect.",
  please_enter_the_password: 'Please enter the password.',
  the_password_must_be_at_least: 'The password must be at least 8 characters with at least one letter, number and special character.',
  please_enter_the_cpassword: 'Please enter the confirm password.',
  the_entered_passwords_do_not_match: 'The entered passwords do not match.',
  please_enter_the_email_and_password: 'Please enter the email and password.',

  patent_pending: 'Patent Pending',
  welcome_lets_get_started: "Welcome, Let’s get\nstarted!",
  create_an_account: 'Create an Account',
  full_name: 'Full Name',
  company_name: 'Company Name',
  create_account: 'Create Account',
  contact_number: 'Contact Number',
  enter_full_name: 'Enter Full Name',
  enter_company_name: 'Enter Company Name',
  enter_contact_number: 'Enter Contact Number',
  enter_confirm_password: 'Enter Confirm Password',
  please_enter_the_full_name: "Please enter the full name.",
  please_enter_the_company_name: 'Please enter the company name.',
  please_enter_the_contact_number: 'Please enter the contact number.',
  please_enter_least_of_ten_number: 'Please enter least of 10 number.',
  enter_your_email_address_to_receive_a_reset_link: 'Enter your email\naddress to receive a\nreset link',
  forgot_password:'Forgot Password',
}
